version: '3.9'

services:
  mongodb:
    container_name: mongodb_upload
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /docker/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=xrimir
      - MONGO_INITDB_ROOT_PASSWORD=itssecret